[project]
name = "resource-fula-ordboken"
version = "0.2.0"
description = "Default template for PDM package"
authors = [
    { name = "Språkbanken Text", email = "sb-info@svenska.gu.se" },
    { name = "Kristoffer Andersson", email = "kristoffer.andersson@gu.se" },
]
dependencies = [
    "json-arrays>=0.15.0",
    "typer>=0.12.3",
    "tqdm>=4.66.2",
    "karp-lex-types>=0.7.2",
    "simple-archive>=0.3.0",
    "chardet>=5.2.0",
    "orjson>=3.10.3",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
resource-fula-ordboken = "resource_fula_ordboken.cli:subapp"

[dependency-groups]
dev = [
    "bump-my-version>=0.32.2",
    "mypy>=1.15.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.7",
]
